const fs = require('fs');

let content = fs.readFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', 'utf8');

const replacements = [
    [/Seguran.a/g, 'Segurança'],
    [/prote..o/g, 'proteção'],
    [/prote.o/g, 'proteção'],
    [/invas.es/g, 'invasões'],
    [/instala..o/g, 'instalação'],
    [/instala.o/g, 'instalação'],
    [/fam.lia/g, 'família'],
    [/im.vel/g, 'imóvel'],
    [/Or.amento/g, 'Orçamento'],
    [/In.cio/g, 'Início'],
    [/Inova..o/g, 'Inovação'],
    [/Inova.o/g, 'Inovação'],
    [/Prote..o/g, 'Proteção'],
    [/Prote.o/g, 'Proteção'],
    [/Patrim.nio/g, 'Patrimônio'],
    [/patrim.nio/g, 'patrimônio'],
    [/resist.ncia/g, 'resistência'],
    [/est.tica/g, 'estética'],
    [/esp.rito/g, 'espírito'],
    [/seguran.a/g, 'segurança'],
    [/experi.ncia/g, 'experiência'],
    [/Din.mico/g, 'Dinâmico'],
    [/Instala.es/g, 'Instalações'],
    [/Instala..o/g, 'Instalação'],
    [/Instala.o/g, 'Instalação'],
    [/Metr./g, 'Metrô'],
    [/espa.os/g, 'espaços'],
    [/instala.es/g, 'instalações'],
    [/v..o/g, 'vão'],
    [/v.o/g, 'vão'],
    [/al.m/g, 'além'],
    [/solu.es/g, 'soluções'],
    [/t.ticas/g, 'táticas'],
    [/Implac.vel/g, 'Implacável'],
    [/L.minas/g, 'Lâminas'],
    [/r.gida/g, 'rígida'],
    [/a.o/g, 'aço'],
    [/intrus..o/g, 'intrusão'],
    [/intrus.o/g, 'intrusão'],
    [/Per.metro/g, 'Perímetro'],
    [/per.metros/g, 'perímetros'],
    [/.rea/g, 'área'],
    [/Conclu.do_/g, 'Concluído_'],
    [/Valoriza..o/g, 'Valorização'],
    [/Valoriza.o/g, 'Valorização'],
    [/Im.vel/g, 'Imóvel'],
    [/respeit.veis/g, 'respeitáveis'],
    [/N.s/g, 'Nós'],
    [/Conte.do/g, 'Conteúdo'],
    [/Ess.ncia/g, 'Essência'],
    [/Tradi..o/g, 'Tradição'],
    [/Tradi.o/g, 'Tradição'],
    [/ind.stria/g, 'indústria'],
    [/alt.ssima/g, 'altíssima'],
    [/Vis..o/g, 'Visão'],
    [/Vis.o/g, 'Visão'],
    [/mat.rias/g, 'matérias'],
    [/est.tico/g, 'estético'],
    [/implac.vel/g, 'implacável'],
    [/dedica..o/g, 'dedicação'],
    [/dedica.o/g, 'dedicação'],
    [/inova.es/g, 'inovações'],
    [/fam.lias/g, 'famílias'],
    [/neg.cios/g, 'negócios'],
    [/cen.rios/g, 'cenários'],
    [/invas..o/g, 'invasão'],
    [/invas.o/g, 'invasão'],
    [/per.metro/g, 'perímetro'],
    [/padr.es/g, 'padrões'],
    [/t.cnicos/g, 'técnicos'],
    [/inflex.veis/g, 'inflexíveis'],
    [/n..o/g, 'não'],
    [/n.o/g, 'não'],
    [/m..o/g, 'mão'],
    [/m.o/g, 'mão'],
    [/execu..o/g, 'execução'],
    [/execu.o/g, 'execução'],
    [/M..o/g, 'Mão'],
    [/M.o/g, 'Mão'],
    [/Servi.o/g, 'Serviço'],
    [/milim.trica/g, 'milimétrica'],
    [/insuper.vel/g, 'insuperável'],
    [/Satisfa..o/g, 'Satisfação'],
    [/Satisfa.o/g, 'Satisfação'],
    [/.nico/g, 'único'],
    [/aceit.vel/g, 'aceitável'],
    [/Servi.os/g, 'Serviços'],
    [/Cat.logo/g, 'Catálogo'],
    [/Lan.a/g, 'Lança'],
    [/pr.tica/g, 'prática'],
    [/resid.ncias/g, 'residências'],
    [/provis.rio/g, 'provisório'],
    [/N..o/g, 'Não'],
    [/N.o/g, 'Não'],
    [/amanh./g, 'amanhã'],
    [/avalia..o/g, 'avaliação'],
    [/avalia.o/g, 'avaliação'],
    [/or.amento/g, 'orçamento'],
    [/voc./g, 'você'],
    [/Se.es/g, 'Seções'],
    [/T.tica/g, 'Tática'],
    [/Informa.es/g, 'Informações'],
    [/Endere.o/g, 'Endereço'],
    [/n.\s/g, 'nº '],
    [/S.b/g, 'Sáb'],
    [/R.pido/g, 'Rápido'],
    [/n.meros/g, 'números'],
    [/Pr.ximo/g, 'Próximo'],
    [/Localiza..o/g, 'Localização'],
    [/Localiza.o/g, 'Localização'],
    [/endere.o/g, 'endereço'],
    [/n.mero/g, 'número'],
    [/log.stica/g, 'logística'],
    [/.sltimo/g, 'Último'],
    [/.ltimo/g, 'Último']
];

for (const [regex, replacement] of replacements) {
    content = content.replace(regex, replacement);
}

fs.writeFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', content, 'utf8');
console.log('Fixed using regex with catch-all dot for corrupted bytes');
