const fs = require('fs');
let content = fs.readFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', 'utf8');

// Replacements where  is literal \ufffd and other weird chars
const replacements = {
    'Seguran\ufffda': 'Segurança',
    'prote\ufffd\u01dco': 'proteção',
    'invas\ufffdes': 'invasões',
    'instala\ufffd\u01dco': 'instalação',
    'fam\ufffdlia': 'família',
    'im\ufffdvel': 'imóvel',
    'Or\ufffdamen\?o': 'Orçamento',
    'Or\ufffdamento': 'Orçamento',
    'In\ufffdcio': 'Início',
    'In\?ova\ufffd\u01dco': 'Inovação',
    'Inova\ufffd\u01dco': 'Inovação',
    'Prote\ufffd\u01dco': 'Proteção',
    'Patrim\ufffdnio': 'Patrimônio',
    'patrim\ufffdnio': 'patrimônio',
    'resist\u01e6ncia': 'resistência',
    'est\u01f8tica': 'estética',
    'esp\ufffdrito': 'espírito',
    'seguran\ufffda': 'segurança',
    'experi\u01e6ncia': 'experiência',
    'Din\u01fdmico': 'Dinâmico',
    'Instala\ufffdes': 'Instalações',
    'Instala\ufffd\u01dco': 'Instalação',
    'Metr\ufffd': 'Metrô',
    'espa\ufffdos': 'espaços',
    'instala\ufffdes': 'instalações',
    'v\u01dco': 'vão',
    'al\u01f8m': 'além',
    'solu\ufffdes': 'soluções',
    't\u01edticas': 'táticas',
    'Implac\u01edvel': 'Implacável',
    'L\u01fdminas': 'Lâminas',
    'r\ufffdgida': 'rígida',
    'a\ufffdo': 'aço',
    'intrus\u01dco': 'intrusão',
    'Per\ufffdmetro': 'Perímetro',
    'per\ufffdmetros': 'perímetros',
    '\u01edrea': 'área',
    'Conclu\ufffddo_': 'Concluído_',
    'Valoriza\ufffd\u01dco': 'Valorização',
    'Im\ufffdvel': 'Imóvel',
    'respeit\u01edveis': 'respeitáveis',
    'N\ufffds': 'Nós',
    'Conte\u01e5do': 'Conteúdo',
    'Ess\u01e6ncia': 'Essência',
    'Tradi\ufffd\u01dco': 'Tradição',
    'ind\u01e5stria': 'indústria',
    'alt\ufffdssima': 'altíssima',
    'Vis\u01dco': 'Visão',
    'mat\u01f8rias': 'matérias',
    'est\u01f8tico': 'estético',
    'implac\u01edvel': 'implacável',
    'dedica\ufffd\u01dco': 'dedicação',
    'inova\ufffdes': 'inovações',
    'fam\ufffdlias': 'famílias',
    'neg\ufffdcios': 'negócios',
    'cen\u01edrios': 'cenários',
    'invas\u01dco': 'invasão',
    'per\ufffdmetro': 'perímetro',
    'padr\ufffdes': 'padrões',
    't\u01f8cnicos': 'técnicos',
    'inflex\ufffdveis': 'inflexíveis',
    'n\u01dco': 'não',
    'm\u01dco': 'mão',
    'execu\ufffd\u01dco': 'execução',
    'M\u01dco': 'Mão',
    'Servi\ufffdo': 'Serviço',
    'servi\?os': 'serviços',
    'milim\u01f8trica': 'milimétrica',
    'insuper\u01edvel': 'insuperável',
    'Satisfa\ufffd\u01dco': 'Satisfação',
    '\u01e5nico': 'único',
    'aceit\u01edvel': 'aceitável',
    'Servi\ufffdos': 'Serviços',
    'Cat\u01edlogo': 'Catálogo',
    'Lan\ufffda': 'Lança',
    'pr\u01edtica': 'prática',
    'resid\u01e6ncias': 'residências',
    'provis\ufffdrio': 'provisório',
    'N\u01dco': 'Não',
    'amanh\ufffd': 'amanhã',
    'avalia\ufffd\u01dco': 'avaliação',
    'or\ufffdamento': 'orçamento',
    'voc\u01e6': 'você',
    'Se\ufffdes': 'Seções',
    'T\u01edtica': 'Tática',
    'Informa\ufffdes': 'Informações',
    'Endere\ufffdo': 'Endereço',
    'n\ufffd ': 'nº ',
    'n\ufffd\n': 'nº\n',
    'S\u01edb': 'Sáb',
    'R\u01edpido': 'Rápido',
    'n\u01e5meros': 'números',
    'Pr\ufffdximo': 'Próximo',
    'Localiza\ufffd\u01dco': 'Localização',
    'endere\ufffdo': 'endereço',
    'n\u01e5mero': 'número',
    'log\ufffdstica': 'logística',
    '\ufffdsltimo': 'Último',
    'crossorigin\?     <link': 'crossorigin>\n    <link'
};

for (const [corrupted, fixed] of Object.entries(replacements)) {
    // Escape string for regex
    const escaped = corrupted.replace(/[.*+?^\${}()|[\]\\]/g, '\\$&');
    content = content.replace(new RegExp(escaped, 'g'), fixed);
}

fs.writeFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', content, 'utf8');
console.log("Applied exact text fixes.");
