const fs = require('fs');
let content = fs.readFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', 'utf8');

const repairs = {
    'crossorigin\ufffd': 'crossorigin>',
    'In\ufffdovaÃ§Ã£o': 'Inovação',
    'servi\ufffdos': 'serviços',
    'cuida\ufffdo.': 'cuidado.',
    'Instal\ufffdm\ufffdos': 'Instalamos',
    'com\ufffdoco': 'com foco',
    'Dev\ufffdolva': 'Devolva',
    'an\ufffdos': 'anos',
    'DinÃ¢m\ufffdo': 'Dinâmico',
    'Metr\ufffd': 'Metrô',
    'N\ufffdossas': 'Nossas',
    'v\ufffdo': 'vão',
    'Entregam\ufffdos': 'Entregamos',
    'text-\ufffdrea': 'text-area',
    'intrus\ufffdo': 'intrusão',
    'indica\ufffdor': 'indicator',
    'n\ufffdone': 'none',
    'lin\ufffdoin': 'linejoin',
    'Blinda\ufffdo': 'Blindado',
    'com\ufffdometidos': 'comprometidos',
    'Analisano': 'Analisando',
    'Ã¡\ufffdrea': 'área',
    'assegura\ufffdo': 'assegurado',
    'Va\ufffdorizaÃ§Ã£o': 'Valorização',
    'curren\ufffdolor': 'currentColor',
    'm\ufffdodernas': 'modernas',
    'S\ufffdbre': 'Sobre',
    'Quem\ufffdom\ufffdos': 'Quem Somos',
    'definitiv\ufffdo': 'definitivo',
    'indeseja\ufffdos': 'indesejados',
    'a\ufffdo ': 'ao ',
    'Merca\ufffdo': 'Mercado',
    'Va\ufffdorizam\ufffdos': 'Valorizamos',
    'atendimeno': 'atendimento',
    'imedia\ufffdos': 'imediatos',
    'Com\ufffdomisso': 'Compromisso',
    'margin\ufffdottom': 'margin-bottom',
    'tÃ©c\ufffdn\ufffdos': 'técnicos',
    'no abrim\ufffdos': 'não abrimos',
    'abrim\ufffdos': 'abrimos',
    'm\ufffdo ': 'mão ',
    'cam\ufffdo': 'campo',
    'humaniza\ufffdo': 'humanizado',
    'imedia\ufffdo': 'imediato',
    'Ãº\ufffdno': 'único',
    'resulta\ufffdo': 'resultado',
    'documenta\ufffdo': 'documentado',
    'm\ufffdo ou per': 'imóvel ou per',
    'm\ufffdo\?': 'imóvel?',
    'n\ufffd prÃ¡tica': 'na prática',
    'com\ufffdo ': 'como ',
    '\ufffdreal ': 'real ',
    'amanh\ufffdÃ£': 'amanhã',
    'um\ufffdorÃ§ameno': 'um orçamento',
    'sem\ufffdom\ufffdomisso': 'sem compromisso',
    'M\ufffdode': 'Mode',
    'Bran\ufffd': 'Brand',
    'v\ufffdocÃª': 'você',
    'em\ufffdonta\ufffdo': 'em contato',
    '\ufffd€”': '—',
    'OrÃ§amen\ufffdo': 'Orçamento',
    'RÃ¡pido': 'Rápido',
    'n\ufffdº': 'nº',
    'S\ufffdbrinho': 'Sobrinho',
    'n\ufffdome': 'nome',
    'n\ufffdosso': 'nosso',
    'n\ufffdossa': 'nossa',
    'n\ufffdossos': 'nossos',
    'n\ufffdossas': 'nossas',
    'n\ufffdo ': 'no ',
    'n\ufffd ': 'nº ',
    'Ã§Ã£o': 'ção',
    'Ã§Ãµes': 'ções',
    'Ã§': 'ç',
    'Ã£': 'ã',
    'Ã¡': 'á',
    'Ã©': 'é',
    'Ã­': 'í',
    'Ã³': 'ó',
    'Ãº': 'ú',
    'Ã¢': 'â',
    'Ãª': 'ê',
    'Ã´': 'ô',
    'Ãµ': 'õ',
    'Ã': 'Á',
    'Ã‰': 'É',
    'Ã“': 'Ó',
    'Ã‡': 'Ç',
    'Ã‚': 'Â',
    'ÃŠ': 'Ê'
};

for (const [corrupted, fixed] of Object.entries(repairs)) {
    const escaped = corrupted.replace(/[.*+?^\${}()|[\]\\]/g, '\\$&');
    content = content.replace(new RegExp(escaped, 'g'), fixed);
}

// Cleanup any remaining `` by replacing with nothing if it breaks words, but let's be careful.
content = content.replace(/\ufffd/g, '');

fs.writeFileSync('c:\\Users\\Micro\\Downloads\\Geonel Site\\index.html', content, 'utf8');
console.log("Repairs 2 applied.");
